src/Admin/AdminBundle/Entity/Image.php
<?php

namespace Admin\AdminBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Image
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Admin\AdminBundle\Repository\ImageRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Image
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255)
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255)
     */
    private $alt;

    private $file;

    private $tempFilename;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set url
     *
     * @param string $url
     * @return Image
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set alt
     *
     * @param string $alt
     * @return Image
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt
     *
     * @return string
     */
    public function getAlt()
    {
        return $this->alt;
    }

    /**
     * @return mixed
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * @param mixed $file
     */
    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;

        // On vérifie si on avait déjà un fichier pour cette entité
        if($this->url !== null)
        {
            // On sauvegarde l'extension du fichier pour le supprimer plus tard
            $this->tempFilename = $this->url;

            // On réinitialise les valeurs des attributs url et alt
            $this->url = null;
            $this->alt = null;
        }
    }

    /**
     * @ORM\PrePersist()
     * @ORM\PreUpdate()
     */
    public function preUpload()
    {
        if($this->file === null)
        {
            return;
        }

        // l'extension du fichier
        $this->url = $this->file->guessExtension();

        // le nom de fichier
        $this->alt = $this->file->getClientOriginalName();
    }

    /**
     * @ORM\PostPersist()
     * @ORM\PostUpdate()
     */
    public function upload()
    {
        if ($this->file === null)
        {
            return;
        }

        // Si on avait un ancien fichier, on le supprime
        if($this->tempFilename !== null)
        {
            $oldFile = $this->getUploadDir().'/'.$this->id.'.'.$this->tempFilename;
            if (file_exists($oldFile))
            {
                unlink($oldFile);
            }
        }
        // On déplace le fichier envoyé dans le répertoire de notre choix
        $this->file->move(
            $this->getUploadDir(), // Le répertoire de destination
            $this->id.'.'.$this->url // Le nom du fichier à créer, ici « id.extension »
        );
    }

    /**
     * @ORM\PreRemove()
     */
    public function preRemoveUpload()
    {
        // On sauvegarde temporairement le nom du fichier, car il dépend de l'id
        $this->tempFilename = $this->getUploadRootDir().'/'.$this->id.'.'.$this.url;
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        if (file_exists($this->tempFilename))
        {
            unlink($this->tempFilename);
        }
    }

    public function getUploadDir()
    {
        return 'uploads/img';
    }

    public function getUploadRootDir()
    {
        // On retourne le chemin relatif vers l'image pour notre code PHP
        return __DIR__.'/../../../../web'.$this->getUploadDir();
    }
}

src/Admin/AdminBundle/Entity/Produit.php
<?php

namespace Admin\AdminBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Produit
 *
 * @ORM\Table(name="produit")
 * @ORM\Entity(repositoryClass="Admin\AdminBundle\Repository\ProduitRepository")
 */
class Produit
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=255, unique=true)
     */
    private $nom;

    /**
     * @var float
     *
     * @ORM\Column(name="prix", type="float")
     */
    private $prix;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text", nullable=true)
     */
    private $description;

    /**
     * @var bool
     *
     * @ORM\Column(name="actif", type="boolean")
     */
    private $actif;

    /**
     * @var
     *
     * @ORM\ManyToMany(targetEntity="Admin\AdminBundle\Entity\Categorie")
     * @ORM\JoinColumn(nullable=true)
     */
    private $categories;

    /**
     * @var
     *
     * @ORM\OneToOne(targetEntity="Admin\AdminBundle\Entity\Image", cascade={"persist", "remove"})
     */
    private $image;


    public function __construct()
    {
        $this->categories = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nom
     *
     * @param string $nom
     *
     * @return Produit
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set prix
     *
     * @param float $prix
     *
     * @return Produit
     */
    public function setPrix($prix)
    {
        $this->prix = $prix;

        return $this;
    }

    /**
     * Get prix
     *
     * @return float
     */
    public function getPrix()
    {
        return $this->prix;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Produit
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set actif
     *
     * @param boolean $actif
     *
     * @return Produit
     */
    public function setActif($actif)
    {
        $this->actif = $actif;

        return $this;
    }

    /**
     * Get actif
     *
     * @return bool
     */
    public function getActif()
    {
        return $this->actif;
    }

    /**
     * Add category
     *
     * @param \Admin\AdminBundle\Entity\Categorie $category
     *
     * @return Produit
     */
    public function addCategory(\Admin\AdminBundle\Entity\Categorie $category)
    {
        $this->categories[] = $category;

        return $this;
    }

    /**
     * Remove category
     *
     * @param \Admin\AdminBundle\Entity\Categorie $category
     */
    public function removeCategory(\Admin\AdminBundle\Entity\Categorie $category)
    {
        $this->categories->removeElement($category);
    }

    /**
     * Get categories
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getCategories()
    {
        return $this->categories;
    }

    /**
     * Set image
     *
     * @param \Admin\AdminBundle\Entity\Image $image
     *
     * @return Produit
     */
    public function setImage(\Admin\AdminBundle\Entity\Image $image = null)
    {
        $this->image = $image;

        return $this;
    }

    /**
     * Get image
     *
     * @return \Admin\AdminBundle\Entity\Image
     */
    public function getImage()
    {
        return $this->image;
    }
}

src/Admin/AdminBundle/Form/ProduitType.php
<?php

namespace Admin\AdminBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProduitType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('prix')
            ->add('description')
            ->add('actif')
            ->add('categories', 'entity', array(
                'class'    => 'Admin\AdminBundle\Entity\Categorie',
                'property' => 'nom',
                'multiple' => true,
                'expanded' => true,
                'required' => false
            ))
        ;
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Admin\AdminBundle\Entity\Produit'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'admin_adminbundle_produit';
    }


}

src/Admin/AdminBundle/Controller/ProduitController.php
<?php

namespace Admin\AdminBundle\Controller;

use Admin\AdminBundle\Entity\Produit;
use Admin\AdminBundle\Form\ProduitType;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class ProduitController extends Controller
{
    public function listerAction($page, $idCategorie)
    {
        if ($page < 1) {
            throw $this->createNotFoundException("La page ".$page." n'existe pas.");
        }

        $nbParPage = 10;

        $em = $this->getDoctrine()->getEntityManager();
        if(isset($idCategorie))
        {
            $produits  = $em->getRepository('AdminAdminBundle:Produit')->findByCategorieId($idCategorie, $page, $nbParPage);
        }
        else
        {
            $produits = $em->getRepository('AdminAdminBundle:Produit')->getProduits($page, $nbParPage);
        }

        $nbPages = ceil(count($produits)/$nbParPage);

        // Si la page n'existe pas, on retourne une 404
        if ($page > $nbPages) {
            throw $this->createNotFoundException("La page ".$page." n'existe pas.");
        }

        $categories = $em->getRepository('AdminAdminBundle:Categorie')->findAll();

        return $this->render('@AdminAdmin/Produit/lister.html.twig', array(
            'produits'   => $produits,
            'categories' => $categories,
            'selectedId' => $idCategorie,
            'nbPages'    => $nbPages,
            'page'       => $page
        ));
    }

    public function ajouterAction(Request $request)
    {
        $produit = new Produit();
        $form = $this->createForm(new ProduitType(), $produit);

        if($form->handleRequest($request)->isValid())
        {
            $em = $this->getDoctrine()->getManager();
            $em->persist($produit);
            $em->flush();

            $request->getSession()->getFlashBag()->add('notice', 'Produit bien enregistrée.');

            return $this->redirectToRoute('admin_admin_produits');
        }
        return $this->render('@AdminAdmin/Produit/ajouter.html.twig', array(
            'form_ajout' => $form->createView()
        ));
    }

    public function modifierAction($id, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $produit = $em->getRepository('AdminAdminBundle:Produit')->find($id);

        if($produit === null)
        {
            throw new NotFoundHttpException("Le produit d'id ".$id." n'existe pas.");
        }

        $form = $this->createForm(new ProduitType(), $produit);
        $form->handleRequest($request);

        if($form->isValid())
        {
            $em->flush();
            $request->getSession()->getFlashBag()->add('notice', 'Produit bien modifiée.');
            return $this->redirectToRoute('admin_admin_produits');
        }

        return $this->render('AdminAdminBundle:Produit:modifier.html.twig', array(
            'form_modif' => $form->createView()
        ));
    }
    
    public function supprimerAction($id, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        $produit = $em->getRepository('AdminAdminBundle:Produit')->find($id);

        if($produit === null)
        {
            throw new NotFoundHttpException("Le produit d'id ".$id." n'existe pas.");
        }

        $em->remove($produit);
        $em->flush();
        $request->getSession()->getFlashBag()->add('notice', 'Catégorie bien supprimée');
        return $this->redirectToRoute('admin_admin_produits');
    }

}

src/Admin/AdminBundle/Resources/views/Produit/ajouter.html.twig
{% extends "AdminAdminBundle::layout.html.twig" %}

{% block title %}
    Ajout de produit
{% endblock %}

{% block theblog_body %}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Ajout de produit</h1>
        </div>
    </div><!--/.row-->

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">Formulaire</div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                {{ form_start(form_ajout) }}
                                    {{ form_widget(form_ajout) }}
                                    <button type="submit" class="btn btn-primary">Enregistrer</button>
                                    <a href="{{ path('admin_admin_produits') }}" type="submit" class="btn btn-warning">Annuler</a>
                                {{ form_end(form_ajout) }}
                               
                            </div>
                        </div>
                    </div>
                </div><!--/.row-->


            </div>
        </div><!-- /.col-->
    </div><!-- /.row -->
{% endblock %}

src/Admin/AdminBundle/Resources/views/Produit/lister.html.twig
{% extends "AdminAdminBundle::layout.html.twig" %}

{% block title %}
    Liste des Produits
{% endblock %}

{% block theblog_body %}
    <br>
<div class="col-md-12">

    <div class="panel panel-default panel-table">
        <div class="panel-heading">
            <div class="row">
                <div class="col col-xs-4">
                    <h3 class="panel-title">Liste des Produits</h3>
                </div>
                <div class="col col-xs-4">
                    <select class="selectpicker" data-style="btn-default" onchange="location = this.options[this.selectedIndex].value;">
                        <option value="{{ path('admin_admin_produits') }}">Toute les catégories</option>
                        {% for categorie in categories %}
                            <option
                                value="{{ path('admin_admin_produits', {'idCategorie': categorie.id}) }}"
                                {% if categorie.id == selectedId  %}
                                    selected="selected"
                                {% endif %}
                            >
                                {{ categorie.nom }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col col-xs-4 text-right">
                    <a href="{{ path('admin_admin_ajouter_produit') }}" class="btn btn-sm btn-primary btn-create fa fa-plus"> Ajouter</a>
                </div>
            </div>
        </div>
        <div class="panel-body">
            <table class="table table-striped table-bordered table-list">
                <thead>
                <tr>
                    <th><em class="fa fa-cog"></em></th>
                    <th class="hidden-xs">ID</th>
                    <th>Nom</th>
                    <th>Prix</th>
                    <th>Description</th>
                    <th>Actif</th>
                </tr>
                </thead>
                <tbody>
                {% for produit in produits %}
                <tr>
                        <td align="center">
                            <a href="{{ path('admin_admin_modifier_produit', {'id': produit.id}) }}" class="btn btn-default" data-toggle="tooltip" title="modifier"><em class="fa fa-pencil"></em></a>
                            <a href="{{ path('admin_admin_supprimer_produit', {'id': produit.id}) }}" class="btn btn-danger" data-toggle="tooltip" title="supprimer" onclick="return confirm('Etes vous sure de vouloir supprimer le produit ?')"><em class="fa fa-trash"></em></a>
                        </td>
                        <td class="hidden-xs">{{ produit.id }}</td>
                        <td>
                            {% set img_src=null %}
                            {% if produit.image is not null %}
                                {% set img_src = produit.image.uploadDir ~ '/' ~ produit.image.id ~ '.' ~ produit.image.url %}
                            {% endif %}
                            <a href="#"
                               data-toggle="popover"
                               title="Photo"
                               data-content="<img {% if img_src is not null %}src='{{ asset(img_src) }}'{% endif %} width='150' alt='photo_du_produit'/>"
                            >
                               {{ produit.nom }}
                           </a>
                        </td>
                        <td>{{ produit.prix }}</td>
                        <td>{{ produit.description }}</td>
                        <td align="center">
                            {% if produit.actif %}
                                <a class="btn btn-default" data-toggle="tooltip" title="activé"><em class="fa fa-check-square"></em></a>
                            {% else %}
                                <a class="btn btn-default" data-toggle="tooltip" title="desactivé"><em class="fa fa-minus"></em></a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>

        </div>
        <div class="panel-footer">
            <div class="row">
                <div class="col col-xs-4">Page {{ page }} sur {{ nbPages }}
                </div>
                <div class="col col-xs-8">
                    <ul class="pagination hidden-xs pull-right">
                        {% for p in range(1, nbPages) %}
                            <li{% if p == page %} class="active"{% endif %}>
                                <a href="{{ path('admin_admin_produits', {'page': p}) }}">{{ p }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                    <ul class="pagination visible-xs pull-right">
                        <li><a href="#">«</a></li>
                        <li><a href="#">»</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock theblog_body %}

src/Admin/AdminBundle/Resources/views/Produit/modifier.html.twig
{% extends "AdminAdminBundle::layout.html.twig" %}

{% block title %}
    Modification de produit
{% endblock %}

{% block theblog_body %}
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Modification de produit</h1>
        </div>
    </div><!--/.row-->

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">Formulaire</div>
                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                {{ form_start(form_modif) }}
                                    {{ form_widget(form_modif) }}
                                    <button type="submit" class="btn btn-primary">Enregistrer</button>
                                    <a href="{{ path('admin_admin_produits') }}" type="submit" class="btn btn-warning">Annuler</a>
                                {{ form_end(form_modif) }}
                            </div>
                        </div>
                    </div>
                </div><!--/.row-->


            </div>
        </div><!-- /.col-->
    </div><!-- /.row -->
{% endblock %}